name: Pkg.update
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.5
      - name: Pkg.update
        run: |
          julia --project=. -e 'using Pkg; Pkg.update()'
          PKG_DIFF="$(julia --project=. -e 'using Pkg; Pkg.status(diff=true)')"
          # Escape newlines etc such that ::set-env works correctly with the multiline string,
          # see https://github.community/t/set-output-truncates-multiline-strings/16852/3
          PKG_DIFF="${PKG_DIFF//'%'/'%25'}"
          PKG_DIFF="${PKG_DIFF//$'\n'/'%0A'}"
          PKG_DIFF="${PKG_DIFF//$'\r'/'%0D'}"
          echo $PKG_DIFF
          echo "::set-env name=PKG_DIFF::$PKG_DIFF"
      - name: 'Create pull request'
        uses: peter-evans/create-pull-request@v3 
        with:
          title: 'Automatic Pkg.update()'
          body: |
            Project diff:
            ```
            ${{ env.PKG_DIFF }}
            ```
          commit-message: |
            Automatic Pkg.update() with the following project diff:
            
            ${{ env.PKG_DIFF }}
